// Lista curada de fuentes para el menú (solo lado admin, no se guarda completa en la DB)
export const FONTS_MENU = [
  { name: 'Kanit', url: 'https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Poppins', url: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap', category: 'Sans' },
  { name: 'Inter', url: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Montserrat', url: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Roboto', url: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap', category: 'Sans' },
  { name: 'Nunito', url: 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Mulish', url: 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Source Sans Pro', url: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Open Sans', url: 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Work Sans', url: 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;600;700&display=swap', category: 'Sans' },
  { name: 'Playfair Display', url: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&display=swap', category: 'Classic/Serif' },
  { name: 'Merriweather', url: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap', category: 'Classic/Serif' },
  { name: 'Libre Baskerville', url: 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap', category: 'Classic/Serif' },
  { name: 'Cormorant Garamond', url: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap', category: 'Classic/Serif' },
  { name: 'Dancing Script', url: 'https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;600;700&display=swap', category: 'Handwrite' },
  { name: 'Pacifico', url: 'https://fonts.googleapis.com/css2?family=Pacifico&display=swap', category: 'Handwrite' },
  { name: 'Caveat', url: 'https://fonts.googleapis.com/css2?family=Caveat:wght@400;600;700&display=swap', category: 'Handwrite' },
  { name: 'Great Vibes', url: 'https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap', category: 'Handwrite' },
  { name: 'Bebas Neue', url: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap', category: 'Display' },
  { name: 'Oswald', url: 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;600&display=swap', category: 'Display' },
  { name: 'Anton', url: 'https://fonts.googleapis.com/css2?family=Anton&display=swap', category: 'Display' },
  { name: 'Fjalla One', url: 'https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap', category: 'Display' },
];
